#pragma once

#define INVALID_TRIANGLE_ID (~(0u))

#define TRIANGLE_ID_BITS 32u
#define TRIANGLE_ID_MESHLET_INSTANCE_INDEX_BITS 20u
#define TRIANGLE_ID_MESHLET_TRIANGLE_INDEX_BITS 7u
#define TRIANGLE_ID_MESHLET_INSTANCE_INDEX_MASK ((1u << TRIANGLE_ID_MESHLET_INSTANCE_INDEX_BITS) - 1u)
#define TRIANGLE_ID_MESHLET_TRIANGLE_INDEX_MASK ((1u << TRIANGLE_ID_MESHLET_TRIANGLE_INDEX_BITS) - 1u)
#define TRIANGLE_ID_REMAINING_BITS (TRIANGLE_ID_BITS - TRIANGLE_ID_)MESHLET_INSTANCE_INDEX_BITS - TRIANGLE_ID_MESHLET_TRIANGLE_INDEX_BITS)

// Currently 2,097,152. Causes around 120mb memory use for meshlet instances.
// Allows for 134,217,728 triangle instances to be drawn.
#define TRIANGLE_ID_MAX_MESHLET_INSTANCES (1u << TRIANGLE_ID_MESHLET_INSTANCE_INDEX_BITS)
// Currently 64
#define TRIANGLE_ID_MAX_MESHLET_TRIANGLES (1u << TRIANGLE_ID_MESHLET_TRIANGLE_INDEX_BITS)

#define TRIANGLE_ID_GET_MESHLET_INSTANCE_INDEX(TRIANGLE_ID) ((TRIANGLE_ID >> TRIANGLE_ID_MESHLET_TRIANGLE_INDEX_BITS) & TRIANGLE_ID_MESHLET_INSTANCE_INDEX_MASK)
#define TRIANGLE_ID_GET_MESHLET_TRIANGLE_INDEX(TRIANGLE_ID) (TRIANGLE_ID & TRIANGLE_ID_MESHLET_TRIANGLE_INDEX_MASK)
#define TRIANGLE_ID_MAKE(MESHLLET_INSTANCE_INDEX, MESHLET_TRIANGLE_INDEX) ((MESHLLET_INSTANCE_INDEX << TRIANGLE_ID_MESHLET_TRIANGLE_INDEX_BITS) | MESHLET_TRIANGLE_INDEX)

#define VISBUF_FIRST_PASS 0
#define VISBUF_SECOND_PASS 1